name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    env:
      IMAGE_NAME: "hex_tiny"
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.18.3-otp-27'
              otp: '27.3.1'

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest -f docker/Dockerfile .

